export const displaySchemas = {
  Card: {
    name: 'Card',
    description: 'A card for displaying content with title, description, and optional image',
    category: 'Display',
    icon: '🃏',
    props: {
      title: { type: 'string', default: 'Card Title' },
      description: { type: 'string', default: 'Card description text goes here.' },
      imageUrl: { type: 'string', default: '' },
      imageAlt: { type: 'string', default: '' },
      accentColor: { type: 'string', default: '#2563eb' },
      backgroundColor: { type: 'string', default: '#ffffff' },
      padding: { type: 'string', default: '24px' },
      borderRadius: { type: 'string', default: '12px' },
      shadowSize: { type: 'string', default: 'medium', enum: ['small', 'medium', 'large'] },
    },
    allowedChildren: [],
    defaultStyle: { width: '100%' }
  },
  AlertBox: {
    name: 'AlertBox',
    description: 'An info, warning, error, or success alert message',
    category: 'Display',
    icon: '⚠',
    props: {
      type: { type: 'string', default: 'info', enum: ['info', 'warning', 'error', 'success'] },
      title: { type: 'string', default: 'Alert Title' },
      message: { type: 'string', default: 'Alert message content goes here.' },
    },
    allowedChildren: [],
    defaultStyle: {}
  },
  Hero: {
    name: 'Hero',
    description: 'A full-width hero banner with headline, subheadline, and CTA buttons',
    category: 'Layout',
    icon: '🦸',
    props: {
      headline: { type: 'string', default: 'Build Something Amazing' },
      subheadline: { type: 'string', default: 'The modern way to create websites.' },
      ctaText: { type: 'string', default: 'Get Started' },
      ctaHref: { type: 'string', default: '#' },
      secondaryCtaText: { type: 'string', default: '' },
      secondaryCtaHref: { type: 'string', default: '#' },
      background: { type: 'string', default: 'blue', enum: ['white', 'light', 'dark', 'blue', 'purple', 'green', 'sunset', 'midnight'] },
      backgroundImage: { type: 'string', default: '' },
      textAlign: { type: 'string', default: 'center', enum: ['center', 'left'] },
      textColor: { type: 'string', default: '#ffffff' },
      minHeight: { type: 'string', default: '480px' },
    },
    allowedChildren: [],
    defaultStyle: {}
  },
  Testimonial: {
    name: 'Testimonial',
    description: 'A customer testimonial with quote, author, and star rating',
    category: 'Display',
    icon: '💬',
    props: {
      quote: { type: 'string', default: 'This product completely changed how we work. Highly recommended!' },
      author: { type: 'string', default: 'Jane Smith' },
      role: { type: 'string', default: 'CEO, Acme Corp' },
      avatarUrl: { type: 'string', default: '' },
      rating: { type: 'number', default: 5 },
      accentColor: { type: 'string', default: '#2563eb' },
      backgroundColor: { type: 'string', default: '#ffffff' },
    },
    allowedChildren: [],
    defaultStyle: {}
  },
  Navbar: {
    name: 'Navbar',
    description: 'A page-level navigation bar with logo and links',
    category: 'Layout',
    icon: '🧭',
    props: {
      logoText: { type: 'string', default: 'My Site' },
      links: { type: 'array', default: [{ label: 'Home', href: '#/' }, { label: 'About', href: '#/pages/about' }] },
      backgroundColor: { type: 'string', default: '#ffffff' },
      textColor: { type: 'string', default: '#1e293b' },
      sticky: { type: 'boolean', default: false },
      ctaText: { type: 'string', default: '' },
      ctaHref: { type: 'string', default: '#' },
    },
    allowedChildren: [],
    defaultStyle: {}
  },
  FooterBlock: {
    name: 'FooterBlock',
    description: 'A page-level footer with copyright and links',
    category: 'Layout',
    icon: '🔻',
    props: {
      copyrightText: { type: 'string', default: 'My Site. All rights reserved.' },
      links: { type: 'array', default: [{ label: 'Privacy', href: '#' }, { label: 'Terms', href: '#' }] },
      backgroundColor: { type: 'string', default: '#1e293b' },
      textColor: { type: 'string', default: '#94a3b8' },
      showYear: { type: 'boolean', default: true },
    },
    allowedChildren: [],
    defaultStyle: {}
  },
  PricingCard: {
    name: 'PricingCard',
    description: 'A pricing tier card with features list and CTA',
    category: 'Display',
    icon: '💰',
    props: {
      planName: { type: 'string', default: 'Pro Plan' },
      price: { type: 'string', default: '$29' },
      period: { type: 'string', default: '/month' },
      features: { type: 'array', default: ['Unlimited pages', 'Custom components', 'GitHub storage', 'Priority support'] },
      ctaText: { type: 'string', default: 'Get Started' },
      ctaHref: { type: 'string', default: '#' },
      highlighted: { type: 'boolean', default: false },
      accentColor: { type: 'string', default: '#2563eb' },
      backgroundColor: { type: 'string', default: '#ffffff' },
    },
    allowedChildren: [],
    defaultStyle: {}
  },
  ContactForm: {
    name: 'ContactForm',
    description: 'A contact form that submits to Formspree or any POST endpoint',
    category: 'Interactive',
    icon: '📬',
    props: {
      formAction: { type: 'string', default: '' },
      submitButtonText: { type: 'string', default: 'Send Message' },
      successMessage: { type: 'string', default: "Thanks! We'll get back to you soon." },
      nameLabel: { type: 'string', default: 'Name' },
      emailLabel: { type: 'string', default: 'Email' },
      messageLabel: { type: 'string', default: 'Message' },
      showPhone: { type: 'boolean', default: false },
    },
    allowedChildren: [],
    defaultStyle: {}
  },
};
