import { minTouchSize } from './responsiveStyles';

export const styles = {
  adminApp: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    backgroundColor: '#f8fafc',
  },
  main: {
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  builderLayout: {
    display: 'flex',
    flexDirection: 'row',
    height: '100%',
  },
  builderMain: {
    flex: 1,
    minHeight: 0,
  },
  builderSidebar: {
    width: '320px',
    borderLeft: '1px solid #e2e8f0',
    backgroundColor: '#ffffff',
    padding: '16px',
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  layoutContainer: {
    display: 'flex',
    height: '100%',
    gap: 0,
  },
  layoutEditor: {
    flex: 1,
    minWidth: 0,
    borderRight: '1px solid #e2e8f0',
    overflowY: 'auto',
  },
  layoutPreview: {
    flex: 1,
    minWidth: 0,
    overflowY: 'auto',
    display: typeof window !== 'undefined' && window.innerWidth >= 1024 ? 'block' : 'none',
  },
  loading: {
    padding: '48px 24px',
    textAlign: 'center',
    color: '#64748b',
    fontSize: '1rem',
  },
  notFound: {
    padding: '48px 24px',
    textAlign: 'center',
    color: '#64748b',
    fontSize: '1rem',
  },
  errorPanel: {
    padding: '48px 24px',
    textAlign: 'center',
    backgroundColor: '#fef2f2',
    borderRadius: '12px',
    margin: '24px',
    border: '1px solid #fecaca',
  },
  retryButton: {
    padding: '8px 20px',
    backgroundColor: '#2563eb',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '0.875rem',
    fontWeight: '500',
    cursor: 'pointer',
    ...minTouchSize,
  },
  successBanner: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 24px',
    backgroundColor: '#ecfdf5',
    color: '#065f46',
    borderBottom: '1px solid #10b981',
    gap: '12px',
  },
  dismissButton: {
    background: 'none',
    border: 'none',
    color: '#065f46',
    cursor: 'pointer',
    fontWeight: '500',
    ...minTouchSize,
    fontSize: '1rem',
  },
  welcomeBanner: {
    padding: '16px 24px',
    backgroundColor: '#eff6ff',
    color: '#1e40af',
    borderBottom: '1px solid #93c5fd',
    textAlign: 'center',
    fontSize: '0.95rem',
    fontWeight: 500,
  },
};
