export const styles = {
  container: { display: 'flex', flexDirection: 'column', gap: '24px', height: '100%', overflowY: 'auto', backgroundColor: '#ffffff' },
  containerMobile: { position: 'fixed', bottom: 0, left: 0, right: 0, height: '40vh', maxHeight: 'calc(100vh - 200px)', borderRadius: '16px 16px 0 0', borderTop: '1px solid #e2e8f0', boxShadow: '0 -10px 25px rgba(0, 0, 0, 0.1)', zIndex: 50, overflow: 'hidden', animation: 'slideUp 300ms cubic-bezier(0.4, 0, 0.2, 1)' },
  containerTablet: { width: '200px' },
  mobileOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0, 0, 0, 0.2)', zIndex: 40, animation: 'fadeIn 200ms ease-in' },
  mobileHeader: { display: 'flex', alignItems: 'center', gap: '8px', padding: '16px', borderBottom: '1px solid #e2e8f0', position: 'relative' },
  paletteToggle: { position: 'fixed', bottom: 'calc(40vh + 24px)', right: '24px', width: '52px', height: '52px', borderRadius: '50%', backgroundColor: '#2563eb', color: '#ffffff', border: 'none', fontSize: '1.5rem', cursor: 'pointer', boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)', zIndex: 45, transition: 'all 200ms ease', minHeight: '52px', minWidth: '52px' },
  closeButton: { position: 'absolute', left: '16px', top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', fontSize: '1.5rem', color: '#1e293b', cursor: 'pointer', padding: '4px 8px' },
  section: { display: 'flex', flexDirection: 'column', gap: '12px' },
  heading: { fontSize: '1rem', fontWeight: '600', color: '#1e293b', margin: 0 },
  searchContainer: { position: 'relative', display: 'flex' },
  searchInput: { width: '100%', padding: '12px', border: '1px solid #e2e8f0', borderRadius: '6px', fontSize: '0.875rem', boxSizing: 'border-box' },
  clearSearchButton: { position: 'absolute', right: '8px', top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', color: '#ef4444', fontSize: '1.25rem', cursor: 'pointer', padding: '4px 8px' },
  resultCounter: { color: '#94a3b8', fontSize: '0.75rem', textAlign: 'right', marginTop: '4px' },
  noResults: { color: '#94a3b8', fontSize: '0.875rem', textAlign: 'center', padding: '24px 12px' },
  emptyStateContainer: { padding: '60px 40px', textAlign: 'center', backgroundColor: '#f8fafc', borderRadius: '12px' },
  emptyIcon: { fontSize: '3.5rem', marginBottom: '20px', display: 'block' },
  emptyTitle: { fontSize: '1.125rem', fontWeight: '600', color: '#1f2937', marginBottom: '12px', margin: '0 0 12px 0' },
  emptyDescription: { fontSize: '0.95rem', color: '#6b7280', marginBottom: '24px', lineHeight: '1.6', margin: '0 0 24px 0' },
  palette: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '16px' },
  paletteTablet: { display: 'grid', gridTemplateColumns: '1fr', gap: '12px' },
  paletteMobile: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px', padding: '0 12px' },
  categoryHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 0', cursor: 'pointer', borderBottom: '1px solid #f1f5f9', userSelect: 'none' },
  categoryLabel: { fontSize: '0.75rem', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.5px', color: '#64748b' },
  categoryCount: { fontSize: '0.688rem', color: '#94a3b8', fontWeight: '500' },
  categoryToggle: { background: 'none', border: 'none', fontSize: '0.625rem', color: '#94a3b8', cursor: 'pointer', padding: '2px 4px' },
  categoryItems: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '12px', padding: '8px 0' },
  categoryItemsTablet: { display: 'grid', gridTemplateColumns: '1fr', gap: '8px', padding: '8px 0' },
  categoryItemsMobile: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '8px', padding: '4px 0' },
  card: { display: 'flex', flexDirection: 'column', border: '1px solid #e5e7eb', borderRadius: '8px', cursor: 'grab', transition: 'all 150ms ease-in-out', backgroundColor: '#ffffff', minHeight: '200px', maxHeight: '250px', overflow: 'hidden' },
  cardMobile: { minHeight: 'auto', maxHeight: 'auto', minWidth: '60px', padding: '12px', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '8px' },
  cardTablet: { minHeight: '80px', maxHeight: '100px', flexDirection: 'row', alignItems: 'center', gap: '12px' },
  cardPreview: { height: '80px', backgroundColor: '#f8fafc', borderRadius: '6px', marginBottom: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  cardPreviewMobile: { height: '40px', width: '100%', backgroundColor: '#f8fafc', borderRadius: '4px', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', marginBottom: '0' },
  mobileIconContainer: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '4px', width: '100%', height: '100%', justifyContent: 'center' },
  mobileIcon: { fontSize: '1.5rem', display: 'block' },
  mobileLabel: { fontSize: '0.65rem', fontWeight: '600', color: '#1e293b', textAlign: 'center' },
  cardInfo: { display: 'flex', flexDirection: 'column', gap: '8px' },
  cardHeader: { display: 'flex', alignItems: 'center', gap: '8px', justifyContent: 'space-between' },
  cardName: { fontSize: '0.875rem', fontWeight: '600', color: '#1e293b' },
  componentType: { fontSize: '0.6rem', fontWeight: '700', color: '#2563eb', textTransform: 'uppercase', letterSpacing: '0.5px' },
  cardDescription: { fontSize: '0.75rem', color: '#64748b', lineHeight: '1.3' },
  cardProps: { fontSize: '0.7rem', color: '#94a3b8', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', lineHeight: '1.2' },
  previewContainer: { width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '8px' },
  previewText: { margin: 0, fontSize: '0.75rem', color: '#1e293b' },
  previewHeading: { margin: 0, fontSize: '0.9rem', color: '#1e293b', fontWeight: '600' },
  previewLink: { fontSize: '0.75rem', color: '#2563eb', textDecoration: 'none' },
  previewPlaceholder: { width: '40px', height: '40px', backgroundColor: '#dbeafe', borderRadius: '6px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  previewIcon: { fontSize: '1.5rem' },
  previewBox: { width: '40px', height: '40px', backgroundColor: '#3b82f6', borderRadius: '4px' },
  previewDivider: { width: '50px', height: '2px', backgroundColor: '#cbd5e1' },
  previewList: { margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '4px' },
  previewListItem: { width: '50px', height: '4px', backgroundColor: '#cbd5e1', borderRadius: '2px' },
  previewError: { color: '#ef4444', fontSize: '0.75rem' },
  tree: { display: 'flex', flexDirection: 'column' },
  treeNode: { display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 12px', cursor: 'pointer', transition: 'background-color 150ms, border-left-color 150ms', position: 'relative' },
  treeNodeContent: { display: 'flex', alignItems: 'center', gap: '8px', flex: 1, minWidth: 0 },
  expandButton: { background: 'none', border: 'none', cursor: 'pointer', fontSize: '0.75rem', padding: '2px 4px', color: '#64748b', width: '20px', height: '20px', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  expandPlaceholder: { width: '20px', height: '20px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#cbd5e1', flexShrink: 0 },
  componentIcon: { fontSize: '1rem', flexShrink: 0 },
  nodeTitle: { flex: 1, fontSize: '0.813rem', color: '#1e293b', fontFamily: "'Monaco', 'Courier New', monospace", overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  typeBadge: (color) => ({ padding: '2px 6px', backgroundColor: color + '18', color: color, fontSize: '0.65rem', fontWeight: '600', borderRadius: '3px', fontFamily: "'Monaco', 'Courier New', monospace", flexShrink: 0, whiteSpace: 'nowrap' }),
  nodeActions: { display: 'flex', gap: '4px', opacity: 0.7, flexShrink: 0 },
  actionButton: { background: 'none', border: 'none', cursor: 'pointer', fontSize: '1rem', color: '#2563eb', padding: '2px 4px' },
  deleteButton: { background: 'none', border: 'none', cursor: 'pointer', fontSize: '1.25rem', color: '#ef4444', padding: '2px 4px' },
  modalBackdrop: { position: 'fixed', top: '0', left: '0', right: '0', bottom: '0', backgroundColor: 'rgba(0, 0, 0, 0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: '1000' },
  confirmModal: { backgroundColor: '#ffffff', borderRadius: '12px', boxShadow: '0 25px 50px rgba(0, 0, 0, 0.15)', maxWidth: '500px', width: '90%' },
  confirmContent: { padding: '24px' },
  confirmTitle: { fontSize: '1.125rem', fontWeight: '600', color: '#111827', margin: '0 0 12px 0' },
  confirmMessage: { fontSize: '0.875rem', color: '#4b5563', margin: '0', lineHeight: '1.5' },
  confirmActions: { display: 'flex', gap: '12px', justifyContent: 'flex-end', padding: '0 24px 24px 24px', borderTop: '1px solid #e5e7eb' },
  cancelButton: { padding: '10px 16px', minHeight: '44px', backgroundColor: '#f3f4f6', color: '#6b7280', border: '1px solid #e5e7eb', borderRadius: '8px', fontSize: '0.875rem', fontWeight: '500', cursor: 'pointer', transition: 'all 150ms' },
  destructiveButton: { padding: '10px 16px', minHeight: '44px', backgroundColor: '#ef4444', color: '#ffffff', border: 'none', borderRadius: '8px', fontSize: '0.875rem', fontWeight: '500', cursor: 'pointer', transition: 'all 150ms' },
};
