import { breakpoints, minTouchSize } from './responsiveStyles';

export const styles = {
  container: {
    padding: '16px',
    maxWidth: '800px',
    margin: '0 auto',
    [`@media (min-width: ${breakpoints.tablet + 1}px)`]: {
      padding: '24px',
    },
    [`@media (min-width: ${breakpoints.laptop + 1}px)`]: {
      padding: '32px',
    },
  },
  heading: {
    fontSize: '1.5rem',
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: '20px',
    [`@media (min-width: ${breakpoints.tablet + 1}px)`]: {
      fontSize: '2rem',
      marginBottom: '24px',
    },
  },
  form: { display: 'flex', flexDirection: 'column', gap: '20px' },
  section: { display: 'flex', flexDirection: 'column', gap: '12px' },
  sectionHeading: {
    fontSize: '1rem',
    fontWeight: '600',
    color: '#1e293b',
    [`@media (min-width: ${breakpoints.tablet + 1}px)`]: {
      fontSize: '1.25rem',
    },
  },
  field: { display: 'flex', flexDirection: 'column', gap: '4px' },
  label: { fontSize: '0.875rem', fontWeight: '500', color: '#64748b' },
  input: {
    padding: '12px 12px',
    border: '1px solid #e2e8f0',
    borderRadius: '6px',
    fontSize: '1rem',
    minHeight: '44px',
    width: '100%',
    boxSizing: 'border-box',
  },
  textarea: {
    padding: '12px 12px',
    border: '1px solid #e2e8f0',
    borderRadius: '6px',
    fontSize: '1rem',
    fontFamily: 'inherit',
    minHeight: '120px',
    width: '100%',
    boxSizing: 'border-box',
  },
  addButton: {
    ...minTouchSize,
    padding: '12px 16px',
    backgroundColor: '#f1f5f9',
    color: '#64748b',
    border: '1px solid #e2e8f0',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: '500',
    fontSize: '0.875rem',
  },
  radioGroup: { display: 'flex', flexDirection: 'column', gap: '12px' },
  radioLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '0.875rem',
    color: '#64748b',
    cursor: 'pointer',
    minHeight: '44px',
    padding: '6px 0',
  },
  radio: { width: '18px', height: '18px', cursor: 'pointer', minWidth: '18px' },
  error: { padding: '12px 16px', backgroundColor: '#fee2e2', color: '#7f1d1d', borderRadius: '6px', fontSize: '0.875rem' },
  actions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginTop: '12px',
    [`@media (min-width: ${breakpoints.tablet + 1}px)`]: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
  },
  submitButton: {
    ...minTouchSize,
    padding: '12px 24px',
    backgroundColor: '#2563eb',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: '500',
    fontSize: '0.95rem',
  },
  resetButton: {
    ...minTouchSize,
    padding: '12px 24px',
    backgroundColor: 'transparent',
    color: '#64748b',
    border: '1px solid #e2e8f0',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: '500',
    fontSize: '0.95rem',
  },
};
