export const styles = {
  container: { padding: '32px', maxWidth: '800px', margin: '0 auto' },
  heading: { fontSize: '2rem', fontWeight: '700', color: '#1e293b', marginBottom: '24px' },
  form: { display: 'flex', flexDirection: 'column', gap: '24px' },
  section: { display: 'flex', flexDirection: 'column', gap: '16px' },
  sectionHeading: { fontSize: '1.25rem', fontWeight: '600', color: '#1e293b' },
  field: { display: 'flex', flexDirection: 'column', gap: '4px' },
  label: { fontSize: '0.875rem', fontWeight: '500', color: '#64748b' },
  input: { padding: '8px 12px', border: '1px solid #e2e8f0', borderRadius: '6px', fontSize: '1rem' },
  textarea: { padding: '8px 12px', border: '1px solid #e2e8f0', borderRadius: '6px', fontSize: '1rem', fontFamily: 'inherit' },
  addButton: { padding: '10px 16px', backgroundColor: '#f1f5f9', color: '#64748b', border: '1px solid #e2e8f0', borderRadius: '6px', cursor: 'pointer' },
  radioGroup: { display: 'flex', flexDirection: 'column', gap: '8px' },
  radioLabel: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.875rem', color: '#64748b', cursor: 'pointer' },
  radio: { width: '16px', height: '16px', cursor: 'pointer' },
  error: { padding: '12px 16px', backgroundColor: '#fee2e2', color: '#7f1d1d', borderRadius: '6px', fontSize: '0.875rem' },
  actions: { display: 'flex', gap: '12px', justifyContent: 'flex-end' },
  submitButton: { padding: '10px 16px', backgroundColor: '#2563eb', color: '#ffffff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: '500' },
  resetButton: { padding: '10px 16px', backgroundColor: 'transparent', color: '#64748b', border: 'none', borderRadius: '6px', cursor: 'pointer' },
};
