export const styles = {
  container: { display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: '#f8fafc' },
  loading: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh', color: '#64748b', fontSize: '1rem' },
  hamburgerButton: { display: 'none', background: 'none', border: 'none', fontSize: '1.5rem', cursor: 'pointer', color: '#1e293b', padding: '4px 8px' },
  backButton: { padding: '12px 16px', backgroundColor: '#f1f5f9', color: '#1e293b', border: '1px solid #e2e8f0', borderRadius: '6px', fontSize: '0.875rem', fontWeight: '600', cursor: 'pointer', margin: '16px', marginBottom: '0' },
  searchInput: { flex: 1, padding: '8px 12px', border: '1px solid #e2e8f0', borderRadius: '6px', fontSize: '0.875rem', fontFamily: 'inherit' },
  filterSelect: { padding: '8px 12px', border: '1px solid #e2e8f0', borderRadius: '6px', fontSize: '0.875rem', backgroundColor: '#ffffff', fontFamily: 'inherit', cursor: 'pointer' },
  componentsList: { display: 'flex', flexDirection: 'column' },
  componentCard: { padding: '16px', borderBottom: '1px solid #e2e8f0', cursor: 'pointer', transition: 'background-color 150ms', userSelect: 'none' },
  componentCardActive: { backgroundColor: '#dbeafe' },
  cardHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px', gap: '8px' },
  componentName: { margin: 0, fontSize: '0.95rem', fontWeight: '600', color: '#1e293b', flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis' },
  customBadge: { padding: '2px 8px', backgroundColor: '#fecaca', color: '#7f1d1d', fontSize: '0.7rem', borderRadius: '3px', fontWeight: '600', whiteSpace: 'nowrap' },
  componentDesc: { margin: '0 0 12px 0', fontSize: '0.8rem', color: '#64748b', lineHeight: '1.4', overflow: 'hidden', textOverflow: 'ellipsis', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical' },
  cardFooter: { display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', color: '#94a3b8', flexWrap: 'wrap', gap: '8px' },
  propCount: { fontWeight: '500' },
  usageCount: { fontWeight: '500', color: '#10b981' },
  detailHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '24px', borderBottom: '1px solid #e2e8f0', gap: '12px', flexWrap: 'wrap' },
  detailTitle: { margin: 0, fontSize: '1.875rem', fontWeight: '700', color: '#1e293b', minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis' },
  deleteButton: { padding: '8px 16px', backgroundColor: '#fecaca', color: '#7f1d1d', border: 'none', borderRadius: '6px', fontSize: '0.875rem', fontWeight: '600', cursor: 'pointer', transition: 'background-color 150ms', whiteSpace: 'nowrap' },
  confirmDialog: { padding: '12px 24px', backgroundColor: '#fee2e2', borderBottom: '1px solid #fecaca', color: '#7f1d1d', fontSize: '0.875rem' },
  confirmActions: { display: 'flex', gap: '8px', marginTop: '12px', flexWrap: 'wrap' },
  confirmDeleteBtn: { padding: '6px 12px', backgroundColor: '#dc2626', color: '#ffffff', border: 'none', borderRadius: '4px', fontSize: '0.875rem', fontWeight: '600', cursor: 'pointer' },
  confirmCancelBtn: { padding: '6px 12px', backgroundColor: '#f3f4f6', color: '#1f2937', border: 'none', borderRadius: '4px', fontSize: '0.875rem', fontWeight: '600', cursor: 'pointer' },
  section: { marginBottom: '32px' },
  sectionTitle: { margin: '0 0 12px 0', fontSize: '0.95rem', fontWeight: '600', color: '#1e293b' },
  sectionText: { margin: 0, color: '#64748b', fontSize: '0.875rem', lineHeight: '1.6' },
  usageList: { margin: 0, padding: 0, listStyle: 'none' },
  usageItem: { padding: '8px 12px', backgroundColor: '#f1f5f9', borderRadius: '4px', marginBottom: '6px', fontSize: '0.875rem', color: '#475569' },
  propField: { padding: '12px', backgroundColor: '#f8fafc', borderRadius: '6px', border: '1px solid #e2e8f0' },
  propLabel: { display: 'block', marginBottom: '8px', fontSize: '0.875rem', fontWeight: '600', color: '#1e293b' },
  propType: { marginLeft: '4px', color: '#64748b', fontWeight: '400', fontSize: '0.8rem' },
  defaultValue: { display: 'block', marginTop: '8px', fontSize: '0.75rem', color: '#94a3b8', fontStyle: 'italic' },
  previewArea: { padding: '16px', backgroundColor: '#f1f5f9', borderRadius: '6px', border: '1px solid #cbd5e1', minHeight: '200px', overflow: 'auto' },
  previewContent: { padding: '16px', backgroundColor: '#ffffff', borderRadius: '4px' },
  previewError: { padding: '16px', backgroundColor: '#fee2e2', color: '#7f1d1d', borderRadius: '4px', fontSize: '0.875rem' },
};
