export const styles = {
  container: { padding: '40px 28px', maxWidth: '1400px', margin: '0 auto', backgroundColor: '#ffffff' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '32px', padding: '32px 28px', borderBottom: '1px solid #e2e8f0', background: 'linear-gradient(to bottom, #ffffff, #f8fafc)', boxShadow: '0 2px 8px rgba(0,0,0,0.06)' },
  heading: { margin: 0, fontSize: '2rem', fontWeight: '800', color: '#1e293b', letterSpacing: '-0.5px', textShadow: '0 1px 2px rgba(0,0,0,0.05)' },
  newButton: { padding: '10px 16px', backgroundColor: '#2563eb', color: '#ffffff', border: 'none', borderRadius: '8px', fontSize: '0.875rem', fontWeight: '500', cursor: 'pointer' },
  loading: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '48px', gap: '16px', color: '#64748b' },
  spinner: { width: '48px', height: '48px', border: '4px solid #e2e8f0', borderTop: '4px solid #2563eb', borderRadius: '50%', animation: 'spin 1s linear infinite' },
  modalBackdrop: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, backdropFilter: 'blur(12px)' },
  modal: { backgroundColor: '#ffffff', padding: '32px', borderRadius: '12px', maxWidth: '500px', width: '90%', boxShadow: '0 25px 50px rgba(0,0,0,0.15)' },
  modalTitle: { margin: '0 0 24px', fontSize: '1.5rem', fontWeight: '700', color: '#1e293b' },
  form: { display: 'flex', flexDirection: 'column', gap: '16px' },
  input: { padding: '12px 16px', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1rem', transition: '150ms ease-in-out' },
  modalActions: { display: 'flex', gap: '12px', justifyContent: 'flex-end' },
  createButton: { padding: '10px 16px', backgroundColor: '#2563eb', color: '#ffffff', border: 'none', borderRadius: '8px', fontSize: '0.875rem', fontWeight: '500', cursor: 'pointer' },
  cancelButton: { padding: '10px 16px', backgroundColor: 'transparent', color: '#64748b', border: 'none', borderRadius: '8px', fontSize: '0.875rem', fontWeight: '500', cursor: 'pointer' },
  error: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px 20px', marginBottom: '24px', background: 'linear-gradient(to right, #fee2e2, #fecaca)', border: '2px solid #ef4444', borderRadius: '12px', color: '#7f1d1d', fontWeight: '600', letterSpacing: '-0.2px', boxShadow: '0 4px 12px rgba(239,68,68,0.2)' },
  dismissButton: { background: 'none', border: 'none', color: '#7f1d1d', fontSize: '1.5rem', cursor: 'pointer', padding: '0 8px' },
  emptyState: { padding: '48px 28px', textAlign: 'center', color: '#64748b', fontSize: '1rem', border: '2px dashed #cbd5e1', borderRadius: '8px', backgroundColor: '#f8fafc', minHeight: '300px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '24px', padding: '28px' },
};
